DROP TABLE IF EXISTS USER_ROLES;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS USER;

CREATE TABLE USER (ID BIGINT NOT NULL AUTO_INCREMENT, USERNAME VARCHAR(255), PASSWORD VARCHAR(255), PRIMARY KEY (ID));

INSERT INTO USER (id, username, password) VALUES (1, 'admin', '$2a$10$xQ6i6RmFAxlEnhFflbsOC.5KpKBuHhUHJWM7.OHRHYJrmiLByizoy');
INSERT INTO USER (id, username, password) VALUES (2, 'seller', '$2a$10$.X4ApFrpq4whm7K2Ag9KPuE4bHuOAldTwDfvVerw5ILA8Cu3r2sOG');
INSERT INTO USER (id, username, password) VALUES (3, 'buyer', '$2a$10$yIvq/GqHlv0RpU7sl./HluZ50mS5BDbmX22m7n3QwtRZsh2KbKEoO');


CREATE TABLE ROLE (ID BIGINT AUTO_INCREMENT, DESCRIPTION VARCHAR(255), NAME VARCHAR(255), PRIMARY KEY (ID));

INSERT INTO role (id, description, name) VALUES (1, 'Admin role', 'ADMIN');
INSERT INTO role (id, description, name) VALUES (2, 'Seller role', 'SELLER');
INSERT INTO role (id, description, name) VALUES (3, 'Buyer role', 'BUYER');

CREATE TABLE USER_ROLES (USER_ID BIGINT NOT NULL, ROLE_ID BIGINT NOT NULL, PRIMARY KEY (USER_ID, ROLE_ID));

ALTER TABLE USER_ROLES ADD CONSTRAINT FK_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID);

ALTER TABLE USER_ROLES ADD CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (ID);

INSERT INTO user_roles (user_id, role_id) VALUES (1, 1);
INSERT INTO user_roles (user_id, role_id) VALUES (2, 2);
INSERT INTO user_roles (user_id, role_id) VALUES (3, 3);
